import type { LabResultItem } from "@/model/LabResultItem";

export const MOCK_LAB_RESULTS: LabResultItem[] = [
  {
    id: "lab-cbc",
    tab: "recent",
    section: "waiting",
    testName: "CBC with differential",
    statusLabel: "Waiting",
    status: "waiting",
    resultDateLine: "Results from: April 3, 2026",
    orderedByLine: "Ordered by: Dr. J. Kim",
    showViewResults: false,
  },
  {
    id: "lab-liquid",
    tab: "recent",
    section: "completed",
    testName: "Liquid panel",
    statusLabel: "New",
    status: "new",
    resultDateLine: "Results from: April 3, 2026",
    orderedByLine: "Ordered by: Dr. J. Kim",
    showViewResults: true,
  },
  {
    id: "lab-past",
    tab: "past",
    section: "completed",
    testName: "Liquid panel",
    resultDateLine: "Results from: April 3, 2026",
    orderedByLine: "Ordered by: Dr. J. Kim",
    showViewResults: true,
  },
  {
    id: "lab-past-2",
    tab: "past",
    section: "completed",
    testName: "Liquid panel",
    resultDateLine: "Results from: April 3, 2026",
    orderedByLine: "Ordered by: Dr. J. Kim",
    showViewResults: true,
  },
  {
    id: "lab-past-3",
    tab: "past",
    section: "completed",
    testName: "Liquid panel",
    resultDateLine: "Results from: April 3, 2026",
    orderedByLine: "Ordered by: Dr. J. Kim",
    showViewResults: true,
  },
  {
    id: "lab-past-4",
    tab: "past",
    section: "completed",
    testName: "Liquid panel",
    resultDateLine: "Results from: April 3, 2026",
    orderedByLine: "Ordered by: Dr. J. Kim",
    showViewResults: true,
  },
];
