import { FIGMA_HOME_ASSETS } from "@/constants/figmaAssets";
import { PatientPortalSummary } from "@/model/PatientPortalSummary";

export const MOCK_PORTAL_SUMMARY: PatientPortalSummary = {
  memberPortalTitle: "Member Portal",
  patientFirstName: "Jane",
  sidebarNav: [
    { kind: "link", id: "home", label: "Home" },
    { kind: "spacer" },
    { kind: "link", id: "messages", label: "Messages", showMessageDot: true },
    { kind: "spacer" },
    { kind: "link", id: "appointments", label: "Appointments" },
    { kind: "spacer" },
    { kind: "divider", line: "_______________" },
    { kind: "spacer" },
    { kind: "link", id: "prescriptions", label: "Prescriptions" },
    { kind: "spacer" },
    { kind: "link", id: "lab", label: "Lab results" },
    { kind: "spacer" },
    { kind: "link", id: "questionnaires", label: "Questionnaires" },
    { kind: "spacer" },
    { kind: "link", id: "documents", label: "Documents" },
    { kind: "spacer" },
    { kind: "divider", line: "________________________" },
    { kind: "spacer" },
    { kind: "link", id: "insurance", label: "Insurance" },
    { kind: "spacer" },
    { kind: "link", id: "billing", label: "Billing" },
    { kind: "spacer" },
    { kind: "link", id: "account", label: "Account" },
    { kind: "spacer" },
    { kind: "divider", line: "________________________" },
    { kind: "spacer" },
    { kind: "link", id: "logout", label: "Log Out" },
  ],
  upcomingSectionTitle: "Upcoming appointment",
  helpSectionTitle: "How can we help you today?",
  homeAppointment: {
    dayNumber: "14",
    monthLabel: "April",
    providerLine: "Follow-up with Dr. J Kim",
    timeLine: "at 3:50 PM ET - 4:10 PM ET",
    joinVideoLabel: "Join Video",
  },
  messageHeadline: "View 3 new messages",
  messageAvatarUrl: FIGMA_HOME_ASSETS.messageAvatarRing,
  messageIconUrl: FIGMA_HOME_ASSETS.messageIconOverlay,
  quickActions: [
    { id: "apt", label: "Request an appointment" },
    { id: "refill", label: "Request a prescription refill" },
    { id: "msg", label: "Send a message to my care team" },
  ],
};
